In [6]:
import numpy.ma as ma
import numpy
import pygrib

grib='grib/multi_1.glo_30m.tp.201501.grb2';
grbs=pygrib.open(grib)
# Remember that indexing in Python starts at zero.
grbs.read(1)[0]

list=[]
for i in range(249):
    grb = grbs.select()[i] 
    data=grb.values
    lat,lon = grb.latlons()
    #print lon
    data, lats, lons = grb.data(lat1=1.6,lat2=2.2,lon1=202.5,lon2=202.9)
    #data.tolist()
    list.append(ma.getdata(data))
    tp0 = numpy.hstack(list)
    print tp0

tp = tp0.ravel()

numpy.save('tp_0360.npy',tp)

[[ 9.62]]
[[ 9.62  9.57]]
[[ 9.62  9.57  9.52]]
[[ 9.62  9.57  9.52  9.43]]
[[ 9.62  9.57  9.52  9.43  9.23]]
[[ 9.62  9.57  9.52  9.43  9.23  9.03]]
[[ 9.62  9.57  9.52  9.43  9.23  9.03  8.86]]
[[ 9.62  9.57  9.52  9.43  9.23  9.03  8.86  8.55]]
[[ 9.62  9.57  9.52  9.43  9.23  9.03  8.86  8.55  8.43]]
[[ 9.62  9.57  9.52  9.43  9.23  9.03  8.86  8.55  8.43  8.41]]
[[ 9.62  9.57  9.52  9.43  9.23  9.03  8.86  8.55  8.43  8.41  8.41]]
[[ 9.62  9.57  9.52  9.43  9.23  9.03  8.86  8.55  8.43  8.41  8.41  8.42]]
[[ 9.62  9.57  9.52  9.43  9.23  9.03  8.86  8.55  8.43  8.41  8.41  8.42
   8.44]]
[[ 9.62  9.57  9.52  9.43  9.23  9.03  8.86  8.55  8.43  8.41  8.41  8.42
   8.44  8.44]]
[[ 9.62  9.57  9.52  9.43  9.23  9.03  8.86  8.55  8.43  8.41  8.41  8.42
   8.44  8.44  8.43]]
[[ 9.62  9.57  9.52  9.43  9.23  9.03  8.86  8.55  8.43  8.41  8.41  8.42
   8.44  8.44  8.43  8.42]]
[[ 9.62  9.57  9.52  9.43  9.23  9.03  8.86  8.55  8.43  8.41  8.41  8.42
   8.44  8.44  8.43  8.42  8.39]]
[[ 9

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47]]
[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43]]
[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  1

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47]]
[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78]]
[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33]]
[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72]]
[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37]]
[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13]]
[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13]]

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

[[  9.62   9.57   9.52   9.43   9.23   9.03   8.86   8.55   8.43   8.41
    8.41   8.42   8.44   8.44   8.43   8.42   8.39   8.38   8.38   8.44
    8.57   8.72   9.17   9.16   9.09   9.04   9.    11.91  11.77  11.64
   11.49  11.15  11.    10.9    8.76   8.73   8.71   8.66   8.59  15.52
    8.43   8.39   8.42   8.52   8.67   8.74   8.66   8.56   8.47   8.43
    8.44   8.47   8.52   8.6    8.71   8.84   8.85   8.8    8.74   8.65
    8.59   8.54   8.51   8.48   8.44   8.4    8.38   8.36  16.47  16.16
   15.59  15.32  14.97  14.42  14.16  13.6   13.33  13.09  12.77  12.6
    8.88   8.87   8.83   8.78   8.72   8.6    8.52  16.21  15.61  15.2
   14.76  14.48  14.2   13.96  13.69  13.46  13.33  13.23  13.02  12.72
   12.58  12.48  12.37  11.91  11.71  11.64  11.56  10.44  10.72  10.77
   10.83  10.87  16.28  15.39  13.97  13.85  13.39  12.94  12.68  12.37
   12.11  11.95  11.83  11.7   11.53  11.46  11.47  11.48  11.41  11.13
   16.68  16.3   15.84  15.48  14.96  14.65  14.42  14.25  14.13  

In [7]:
import numpy.ma as ma
import numpy
import pygrib

grib='grib/multi_1.glo_30m.dp.201501.grb2';
grbs=pygrib.open(grib)
# Remember that indexing in Python starts at zero.
grbs.read(1)[0]

list=[]
for i in range(249):
    grb = grbs.select()[i]
    data=grb.values
    lat,lon = grb.latlons()

    data, lats, lons = grb.data(lat1=1.6,lat2=2.2,lon1=202.5,lon2=202.9)
    #data.tolist()
    list.append(ma.getdata(data))
    dp0 = numpy.hstack(list)
    print dp0

dp = dp0.ravel()

numpy.save('dp_0360.npy',dp)

[[ 98.66]]
[[ 98.66  97.23]]
[[ 98.66  97.23  96.31]]
[[ 98.66  97.23  96.31  95.5 ]]
[[ 98.66  97.23  96.31  95.5   92.22]]
[[ 98.66  97.23  96.31  95.5   92.22  93.29]]
[[ 98.66  97.23  96.31  95.5   92.22  93.29  94.17]]
[[ 98.66  97.23  96.31  95.5   92.22  93.29  94.17  90.62]]
[[ 98.66  97.23  96.31  95.5   92.22  93.29  94.17  90.62  90.85]]
[[ 98.66  97.23  96.31  95.5   92.22  93.29  94.17  90.62  90.85  91.27]]
[[ 98.66  97.23  96.31  95.5   92.22  93.29  94.17  90.62  90.85  91.27
   91.72]]
[[ 98.66  97.23  96.31  95.5   92.22  93.29  94.17  90.62  90.85  91.27
   91.72  92.25]]
[[ 98.66  97.23  96.31  95.5   92.22  93.29  94.17  90.62  90.85  91.27
   91.72  92.25  92.86]]
[[ 98.66  97.23  96.31  95.5   92.22  93.29  94.17  90.62  90.85  91.27
   91.72  92.25  92.86  93.53]]
[[ 98.66  97.23  96.31  95.5   92.22  93.29  94.17  90.62  90.85  91.27
   91.72  92.25  92.86  93.53  94.21]]
[[ 98.66  97.23  96.31  95.5   92.22  93.29  94.17  90.62  90.85  91.27
   91.72  92.25  9

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99]]
[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29]]
[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02]]
[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55 

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25]]
[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72]]
[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43 

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47]]
[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39 

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15]]
[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
  

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71]]
[[

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

[[  98.66   97.23   96.31   95.5    92.22   93.29   94.17   90.62   90.85
    91.27   91.72   92.25   92.86   93.53   94.21   94.98   95.8    96.66
    97.39   97.9    97.67   96.84   91.09   89.07   88.12   88.46   89.31
   339.87  340.39  340.43  340.02  346.    345.05  344.09   85.04   90.05
    89.73   89.27   88.79  326.06   88.29   88.26   87.5    85.47   82.47
    50.99   78.29   77.82   77.73   77.65   77.19   76.51   76.1    75.85
    75.51   58.55   58.56   58.21   68.46   66.26   64.51   63.23   62.45
    62.09   62.02   62.11   62.11   62.11  313.45  328.63  329.33  333.76
   337.39  335.85  333.45  336.26  334.18  336.67  336.25  334.87   55.13
    56.1    56.79   57.49   64.9    65.93   67.24  331.92  329.25  330.19
   327.72  328.84  329.42  326.88  328.    328.68  329.    329.05  327.84
   328.63  329.47  330.47  331.92  333.38  336.47  340.44  345.01   21.58
     7.2    16.54   32.28   69.15  337.1   332.26  295.82  306.77  313.35
   297.56  301.64  305.49  280.71  285

In [8]:
import numpy.ma as ma
import numpy
import pygrib

grib='grib/multi_1.glo_30m.hs.201501.grb2';
grbs=pygrib.open(grib)
# Remember that indexing in Python starts at zero.
grbs.read(1)[0]

list=[]
for i in range(249):
    grb = grbs.select()[i] #167 2.52
    data=grb.values
    lat,lon = grb.latlons()

    data, lats, lons = grb.data(lat1=1.6,lat2=2.2,lon1=202.5,lon2=202.9)
    #data.tolist()
    list.append(ma.getdata(data))
    hs0 = numpy.hstack(list)
print hs0

hs = hs0.ravel()

numpy.save('hs_0360.npy',hs)

[[ 2.    2.04  2.11  2.18  2.18  2.16  2.16  2.17  2.15  2.11  2.09  2.09
   2.09  2.08  2.1   2.12  2.13  2.14  2.16  2.19  2.2   2.21  2.22  2.22
   2.21  2.2   2.19  2.18  2.16  2.13  2.1   2.07  2.05  2.03  2.03  2.05
   2.08  2.08  2.1   2.13  2.14  2.14  2.16  2.2   2.21  2.21  2.21  2.19
   2.16  2.12  2.09  2.06  2.02  2.    1.99  1.99  1.98  1.97  1.96  1.97
   1.98  1.98  1.99  1.99  1.99  1.99  1.99  2.    2.04  2.09  2.17  2.28
   2.35  2.38  2.41  2.45  2.49  2.51  2.49  2.45  2.4   2.34  2.27  2.22
   2.17  2.15  2.15  2.15  2.14  2.12  2.1   2.07  2.05  2.03  2.01  1.98
   1.95  1.92  1.89  1.87  1.86  1.84  1.83  1.83  1.82  1.81  1.8   1.8
   1.79  1.8   1.82  1.88  1.95  2.04  2.11  2.16  2.18  2.18  2.17  2.15
   2.13  2.1   2.08  2.06  2.04  2.03  2.02  2.01  2.01  2.03  2.08  2.15
   2.23  2.28  2.31  2.32  2.3   2.28  2.25  2.21  2.17  2.14  2.13  2.13
   2.13  2.14  2.15  2.16  2.17  2.16  2.16  2.15  2.13  2.11  2.1   2.1
   2.09  2.07  2.04  2.02  2.02  2.03  2

In [9]:
dp_gribs = ['grib/multi_1.glo_30m.dp.200502.grb2', 'grib/multi_1.glo_30m.dp.200503.grb2', 'grib/multi_1.glo_30m.dp.200504.grb2', 'grib/multi_1.glo_30m.dp.200505.grb2', 'grib/multi_1.glo_30m.dp.200506.grb2', 'grib/multi_1.glo_30m.dp.200507.grb2', 'grib/multi_1.glo_30m.dp.200508.grb2', 'grib/multi_1.glo_30m.dp.200509.grb2', 'grib/multi_1.glo_30m.dp.200510.grb2', 'grib/multi_1.glo_30m.dp.200511.grb2', 'grib/multi_1.glo_30m.dp.200512.grb2', 'grib/multi_1.glo_30m.dp.200601.grb2', 'grib/multi_1.glo_30m.dp.200602.grb2', 'grib/multi_1.glo_30m.dp.200603.grb2', 'grib/multi_1.glo_30m.dp.200604.grb2', 'grib/multi_1.glo_30m.dp.200605.grb2', 'grib/multi_1.glo_30m.dp.200606.grb2', 'grib/multi_1.glo_30m.dp.200607.grb2', 'grib/multi_1.glo_30m.dp.200608.grb2', 'grib/multi_1.glo_30m.dp.200609.grb2', 'grib/multi_1.glo_30m.dp.200610.grb2', 'grib/multi_1.glo_30m.dp.200611.grb2', 'grib/multi_1.glo_30m.dp.200612.grb2', 'grib/multi_1.glo_30m.dp.200701.grb2', 'grib/multi_1.glo_30m.dp.200702.grb2', 'grib/multi_1.glo_30m.dp.200703.grb2', 'grib/multi_1.glo_30m.dp.200704.grb2', 'grib/multi_1.glo_30m.dp.200705.grb2', 'grib/multi_1.glo_30m.dp.200706.grb2', 'grib/multi_1.glo_30m.dp.200707.grb2', 'grib/multi_1.glo_30m.dp.200708.grb2', 'grib/multi_1.glo_30m.dp.200709.grb2', 'grib/multi_1.glo_30m.dp.200710.grb2', 'grib/multi_1.glo_30m.dp.200711.grb2', 'grib/multi_1.glo_30m.dp.200712.grb2', 'grib/multi_1.glo_30m.dp.200801.grb2', 'grib/multi_1.glo_30m.dp.200802.grb2', 'grib/multi_1.glo_30m.dp.200803.grb2', 'grib/multi_1.glo_30m.dp.200804.grb2', 'grib/multi_1.glo_30m.dp.200805.grb2', 'grib/multi_1.glo_30m.dp.200806.grb2', 'grib/multi_1.glo_30m.dp.200807.grb2', 'grib/multi_1.glo_30m.dp.200808.grb2', 'grib/multi_1.glo_30m.dp.200809.grb2', 'grib/multi_1.glo_30m.dp.200810.grb2', 'grib/multi_1.glo_30m.dp.200811.grb2', 'grib/multi_1.glo_30m.dp.200812.grb2', 'grib/multi_1.glo_30m.dp.200901.grb2', 'grib/multi_1.glo_30m.dp.200902.grb2', 'grib/multi_1.glo_30m.dp.200903.grb2', 'grib/multi_1.glo_30m.dp.200904.grb2', 'grib/multi_1.glo_30m.dp.200905.grb2', 'grib/multi_1.glo_30m.dp.200906.grb2', 'grib/multi_1.glo_30m.dp.200907.grb2', 'grib/multi_1.glo_30m.dp.200908.grb2', 'grib/multi_1.glo_30m.dp.200909.grb2', 'grib/multi_1.glo_30m.dp.200910.grb2', 'grib/multi_1.glo_30m.dp.200911.grb2', 'grib/multi_1.glo_30m.dp.200912.grb2', 'grib/multi_1.glo_30m.dp.201001.grb2', 'grib/multi_1.glo_30m.dp.201002.grb2', 'grib/multi_1.glo_30m.dp.201003.grb2', 'grib/multi_1.glo_30m.dp.201004.grb2', 'grib/multi_1.glo_30m.dp.201005.grb2', 'grib/multi_1.glo_30m.dp.201006.grb2', 'grib/multi_1.glo_30m.dp.201007.grb2', 'grib/multi_1.glo_30m.dp.201008.grb2', 'grib/multi_1.glo_30m.dp.201009.grb2', 'grib/multi_1.glo_30m.dp.201010.grb2', 'grib/multi_1.glo_30m.dp.201011.grb2', 'grib/multi_1.glo_30m.dp.201012.grb2', 'grib/multi_1.glo_30m.dp.201101.grb2', 'grib/multi_1.glo_30m.dp.201102.grb2', 'grib/multi_1.glo_30m.dp.201103.grb2', 'grib/multi_1.glo_30m.dp.201104.grb2', 'grib/multi_1.glo_30m.dp.201105.grb2', 'grib/multi_1.glo_30m.dp.201106.grb2', 'grib/multi_1.glo_30m.dp.201107.grb2', 'grib/multi_1.glo_30m.dp.201108.grb2', 'grib/multi_1.glo_30m.dp.201109.grb2', 'grib/multi_1.glo_30m.dp.201110.grb2', 'grib/multi_1.glo_30m.dp.201111.grb2', 'grib/multi_1.glo_30m.dp.201112.grb2', 'grib/multi_1.glo_30m.dp.201201.grb2', 'grib/multi_1.glo_30m.dp.201202.grb2', 'grib/multi_1.glo_30m.dp.201203.grb2', 'grib/multi_1.glo_30m.dp.201204.grb2', 'grib/multi_1.glo_30m.dp.201205.grb2', 'grib/multi_1.glo_30m.dp.201206.grb2', 'grib/multi_1.glo_30m.dp.201207.grb2', 'grib/multi_1.glo_30m.dp.201208.grb2', 'grib/multi_1.glo_30m.dp.201209.grb2', 'grib/multi_1.glo_30m.dp.201210.grb2', 'grib/multi_1.glo_30m.dp.201211.grb2', 'grib/multi_1.glo_30m.dp.201212.grb2', 'grib/multi_1.glo_30m.dp.201301.grb2', 'grib/multi_1.glo_30m.dp.201302.grb2', 'grib/multi_1.glo_30m.dp.201303.grb2', 'grib/multi_1.glo_30m.dp.201304.grb2', 'grib/multi_1.glo_30m.dp.201305.grb2', 'grib/multi_1.glo_30m.dp.201306.grb2', 'grib/multi_1.glo_30m.dp.201307.grb2', 'grib/multi_1.glo_30m.dp.201308.grb2', 'grib/multi_1.glo_30m.dp.201309.grb2', 'grib/multi_1.glo_30m.dp.201310.grb2', 'grib/multi_1.glo_30m.dp.201311.grb2', 'grib/multi_1.glo_30m.dp.201312.grb2', 'grib/multi_1.glo_30m.dp.201401.grb2', 'grib/multi_1.glo_30m.dp.201402.grb2', 'grib/multi_1.glo_30m.dp.201403.grb2', 'grib/multi_1.glo_30m.dp.201404.grb2', 'grib/multi_1.glo_30m.dp.201405.grb2', 'grib/multi_1.glo_30m.dp.201406.grb2', 'grib/multi_1.glo_30m.dp.201407.grb2', 'grib/multi_1.glo_30m.dp.201408.grb2', 'grib/multi_1.glo_30m.dp.201409.grb2', 'grib/multi_1.glo_30m.dp.201410.grb2', 'grib/multi_1.glo_30m.dp.201411.grb2', 'grib/multi_1.glo_30m.dp.201412.grb2', 'grib/multi_1.glo_30m.dp.201501.grb2', 'grib/multi_1.glo_30m.dp.201502.grb2', 'grib/multi_1.glo_30m.dp.201503.grb2', 'grib/multi_1.glo_30m.dp.201504.grb2', 'grib/multi_1.glo_30m.dp.201505.grb2', 'grib/multi_1.glo_30m.dp.201506.grb2', 'grib/multi_1.glo_30m.dp.201507.grb2', 'grib/multi_1.glo_30m.dp.201508.grb2', 'grib/multi_1.glo_30m.dp.201509.grb2', 'grib/multi_1.glo_30m.dp.201510.grb2', 'grib/multi_1.glo_30m.dp.201511.grb2', 'grib/multi_1.glo_30m.dp.201512.grb2', 'grib/multi_1.glo_30m.dp.201601.grb2', 'grib/multi_1.glo_30m.dp.201602.grb2', 'grib/multi_1.glo_30m.dp.201603.grb2', 'grib/multi_1.glo_30m.dp.201604.grb2', 'grib/multi_1.glo_30m.dp.201605.grb2', 'grib/multi_1.glo_30m.dp.201606.grb2', 'grib/multi_1.glo_30m.dp.201607.grb2', 'grib/multi_1.glo_30m.dp.201608.grb2', 'grib/multi_1.glo_30m.dp.201609.grb2', 'grib/multi_1.glo_30m.dp.201610.grb2', 'grib/multi_1.glo_30m.dp.201611.grb2', 'grib/multi_1.glo_30m.dp.201612.grb2', 'grib/multi_1.glo_30m.dp.201701.grb2', 'grib/multi_1.glo_30m.dp.201702.grb2', 'grib/multi_1.glo_30m.dp.201703.grb2', 'grib/multi_1.glo_30m.dp.201704.grb2', 'grib/multi_1.glo_30m.dp.201705.grb2', 'grib/multi_1.glo_30m.dp.201706.grb2', 'grib/multi_1.glo_30m.dp.201707.grb2', 'grib/multi_1.glo_30m.dp.201708.grb2', 'grib/multi_1.glo_30m.dp.201709.grb2', 'grib/multi_1.glo_30m.dp.201710.grb2', 'grib/multi_1.glo_30m.dp.201711.grb2', 'grib/multi_1.glo_30m.dp.201712.grb2']
hs_gribs = ['grib/multi_1.glo_30m.hs.200502.grb2', 'grib/multi_1.glo_30m.hs.200503.grb2', 'grib/multi_1.glo_30m.hs.200504.grb2', 'grib/multi_1.glo_30m.hs.200505.grb2', 'grib/multi_1.glo_30m.hs.200506.grb2', 'grib/multi_1.glo_30m.hs.200507.grb2', 'grib/multi_1.glo_30m.hs.200508.grb2', 'grib/multi_1.glo_30m.hs.200509.grb2', 'grib/multi_1.glo_30m.hs.200510.grb2', 'grib/multi_1.glo_30m.hs.200511.grb2', 'grib/multi_1.glo_30m.hs.200512.grb2', 'grib/multi_1.glo_30m.hs.200601.grb2', 'grib/multi_1.glo_30m.hs.200602.grb2', 'grib/multi_1.glo_30m.hs.200603.grb2', 'grib/multi_1.glo_30m.hs.200604.grb2', 'grib/multi_1.glo_30m.hs.200605.grb2', 'grib/multi_1.glo_30m.hs.200606.grb2', 'grib/multi_1.glo_30m.hs.200607.grb2', 'grib/multi_1.glo_30m.hs.200608.grb2', 'grib/multi_1.glo_30m.hs.200609.grb2', 'grib/multi_1.glo_30m.hs.200610.grb2', 'grib/multi_1.glo_30m.hs.200611.grb2', 'grib/multi_1.glo_30m.hs.200612.grb2', 'grib/multi_1.glo_30m.hs.200701.grb2', 'grib/multi_1.glo_30m.hs.200702.grb2', 'grib/multi_1.glo_30m.hs.200703.grb2', 'grib/multi_1.glo_30m.hs.200704.grb2', 'grib/multi_1.glo_30m.hs.200705.grb2', 'grib/multi_1.glo_30m.hs.200706.grb2', 'grib/multi_1.glo_30m.hs.200707.grb2', 'grib/multi_1.glo_30m.hs.200708.grb2', 'grib/multi_1.glo_30m.hs.200709.grb2', 'grib/multi_1.glo_30m.hs.200710.grb2', 'grib/multi_1.glo_30m.hs.200711.grb2', 'grib/multi_1.glo_30m.hs.200712.grb2', 'grib/multi_1.glo_30m.hs.200801.grb2', 'grib/multi_1.glo_30m.hs.200802.grb2', 'grib/multi_1.glo_30m.hs.200803.grb2', 'grib/multi_1.glo_30m.hs.200804.grb2', 'grib/multi_1.glo_30m.hs.200805.grb2', 'grib/multi_1.glo_30m.hs.200806.grb2', 'grib/multi_1.glo_30m.hs.200807.grb2', 'grib/multi_1.glo_30m.hs.200808.grb2', 'grib/multi_1.glo_30m.hs.200809.grb2', 'grib/multi_1.glo_30m.hs.200810.grb2', 'grib/multi_1.glo_30m.hs.200811.grb2', 'grib/multi_1.glo_30m.hs.200812.grb2', 'grib/multi_1.glo_30m.hs.200901.grb2', 'grib/multi_1.glo_30m.hs.200902.grb2', 'grib/multi_1.glo_30m.hs.200903.grb2', 'grib/multi_1.glo_30m.hs.200904.grb2', 'grib/multi_1.glo_30m.hs.200905.grb2', 'grib/multi_1.glo_30m.hs.200906.grb2', 'grib/multi_1.glo_30m.hs.200907.grb2', 'grib/multi_1.glo_30m.hs.200908.grb2', 'grib/multi_1.glo_30m.hs.200909.grb2', 'grib/multi_1.glo_30m.hs.200910.grb2', 'grib/multi_1.glo_30m.hs.200911.grb2', 'grib/multi_1.glo_30m.hs.200912.grb2', 'grib/multi_1.glo_30m.hs.201001.grb2', 'grib/multi_1.glo_30m.hs.201002.grb2', 'grib/multi_1.glo_30m.hs.201003.grb2', 'grib/multi_1.glo_30m.hs.201004.grb2', 'grib/multi_1.glo_30m.hs.201005.grb2', 'grib/multi_1.glo_30m.hs.201006.grb2', 'grib/multi_1.glo_30m.hs.201007.grb2', 'grib/multi_1.glo_30m.hs.201008.grb2', 'grib/multi_1.glo_30m.hs.201009.grb2', 'grib/multi_1.glo_30m.hs.201010.grb2', 'grib/multi_1.glo_30m.hs.201011.grb2', 'grib/multi_1.glo_30m.hs.201012.grb2', 'grib/multi_1.glo_30m.hs.201101.grb2', 'grib/multi_1.glo_30m.hs.201102.grb2', 'grib/multi_1.glo_30m.hs.201103.grb2', 'grib/multi_1.glo_30m.hs.201104.grb2', 'grib/multi_1.glo_30m.hs.201105.grb2', 'grib/multi_1.glo_30m.hs.201106.grb2', 'grib/multi_1.glo_30m.hs.201107.grb2', 'grib/multi_1.glo_30m.hs.201108.grb2', 'grib/multi_1.glo_30m.hs.201109.grb2', 'grib/multi_1.glo_30m.hs.201110.grb2', 'grib/multi_1.glo_30m.hs.201111.grb2', 'grib/multi_1.glo_30m.hs.201112.grb2', 'grib/multi_1.glo_30m.hs.201201.grb2', 'grib/multi_1.glo_30m.hs.201202.grb2', 'grib/multi_1.glo_30m.hs.201203.grb2', 'grib/multi_1.glo_30m.hs.201204.grb2', 'grib/multi_1.glo_30m.hs.201205.grb2', 'grib/multi_1.glo_30m.hs.201206.grb2', 'grib/multi_1.glo_30m.hs.201207.grb2', 'grib/multi_1.glo_30m.hs.201208.grb2', 'grib/multi_1.glo_30m.hs.201209.grb2', 'grib/multi_1.glo_30m.hs.201210.grb2', 'grib/multi_1.glo_30m.hs.201211.grb2', 'grib/multi_1.glo_30m.hs.201212.grb2', 'grib/multi_1.glo_30m.hs.201301.grb2', 'grib/multi_1.glo_30m.hs.201302.grb2', 'grib/multi_1.glo_30m.hs.201303.grb2', 'grib/multi_1.glo_30m.hs.201304.grb2', 'grib/multi_1.glo_30m.hs.201305.grb2', 'grib/multi_1.glo_30m.hs.201306.grb2', 'grib/multi_1.glo_30m.hs.201307.grb2', 'grib/multi_1.glo_30m.hs.201308.grb2', 'grib/multi_1.glo_30m.hs.201309.grb2', 'grib/multi_1.glo_30m.hs.201310.grb2', 'grib/multi_1.glo_30m.hs.201311.grb2', 'grib/multi_1.glo_30m.hs.201312.grb2', 'grib/multi_1.glo_30m.hs.201401.grb2', 'grib/multi_1.glo_30m.hs.201402.grb2', 'grib/multi_1.glo_30m.hs.201403.grb2', 'grib/multi_1.glo_30m.hs.201404.grb2', 'grib/multi_1.glo_30m.hs.201405.grb2', 'grib/multi_1.glo_30m.hs.201406.grb2', 'grib/multi_1.glo_30m.hs.201407.grb2', 'grib/multi_1.glo_30m.hs.201408.grb2', 'grib/multi_1.glo_30m.hs.201409.grb2', 'grib/multi_1.glo_30m.hs.201410.grb2', 'grib/multi_1.glo_30m.hs.201411.grb2', 'grib/multi_1.glo_30m.hs.201412.grb2', 'grib/multi_1.glo_30m.hs.201501.grb2', 'grib/multi_1.glo_30m.hs.201502.grb2', 'grib/multi_1.glo_30m.hs.201503.grb2', 'grib/multi_1.glo_30m.hs.201504.grb2', 'grib/multi_1.glo_30m.hs.201505.grb2', 'grib/multi_1.glo_30m.hs.201506.grb2', 'grib/multi_1.glo_30m.hs.201507.grb2', 'grib/multi_1.glo_30m.hs.201508.grb2', 'grib/multi_1.glo_30m.hs.201509.grb2', 'grib/multi_1.glo_30m.hs.201510.grb2', 'grib/multi_1.glo_30m.hs.201511.grb2', 'grib/multi_1.glo_30m.hs.201512.grb2', 'grib/multi_1.glo_30m.hs.201601.grb2', 'grib/multi_1.glo_30m.hs.201602.grb2', 'grib/multi_1.glo_30m.hs.201603.grb2', 'grib/multi_1.glo_30m.hs.201604.grb2', 'grib/multi_1.glo_30m.hs.201605.grb2', 'grib/multi_1.glo_30m.hs.201606.grb2', 'grib/multi_1.glo_30m.hs.201607.grb2', 'grib/multi_1.glo_30m.hs.201608.grb2', 'grib/multi_1.glo_30m.hs.201609.grb2', 'grib/multi_1.glo_30m.hs.201610.grb2', 'grib/multi_1.glo_30m.hs.201611.grb2', 'grib/multi_1.glo_30m.hs.201612.grb2', 'grib/multi_1.glo_30m.hs.201701.grb2', 'grib/multi_1.glo_30m.hs.201702.grb2', 'grib/multi_1.glo_30m.hs.201703.grb2', 'grib/multi_1.glo_30m.hs.201704.grb2', 'grib/multi_1.glo_30m.hs.201705.grb2', 'grib/multi_1.glo_30m.hs.201706.grb2', 'grib/multi_1.glo_30m.hs.201707.grb2', 'grib/multi_1.glo_30m.hs.201708.grb2', 'grib/multi_1.glo_30m.hs.201709.grb2', 'grib/multi_1.glo_30m.hs.201710.grb2', 'grib/multi_1.glo_30m.hs.201711.grb2', 'grib/multi_1.glo_30m.hs.201712.grb2']
tp_gribs = ['grib/multi_1.glo_30m.tp.200502.grb2', 'grib/multi_1.glo_30m.tp.200503.grb2', 'grib/multi_1.glo_30m.tp.200504.grb2', 'grib/multi_1.glo_30m.tp.200505.grb2', 'grib/multi_1.glo_30m.tp.200506.grb2', 'grib/multi_1.glo_30m.tp.200507.grb2', 'grib/multi_1.glo_30m.tp.200508.grb2', 'grib/multi_1.glo_30m.tp.200509.grb2', 'grib/multi_1.glo_30m.tp.200510.grb2', 'grib/multi_1.glo_30m.tp.200511.grb2', 'grib/multi_1.glo_30m.tp.200512.grb2', 'grib/multi_1.glo_30m.tp.200601.grb2', 'grib/multi_1.glo_30m.tp.200602.grb2', 'grib/multi_1.glo_30m.tp.200603.grb2', 'grib/multi_1.glo_30m.tp.200604.grb2', 'grib/multi_1.glo_30m.tp.200605.grb2', 'grib/multi_1.glo_30m.tp.200606.grb2', 'grib/multi_1.glo_30m.tp.200607.grb2', 'grib/multi_1.glo_30m.tp.200608.grb2', 'grib/multi_1.glo_30m.tp.200609.grb2', 'grib/multi_1.glo_30m.tp.200610.grb2', 'grib/multi_1.glo_30m.tp.200611.grb2', 'grib/multi_1.glo_30m.tp.200612.grb2', 'grib/multi_1.glo_30m.tp.200701.grb2', 'grib/multi_1.glo_30m.tp.200702.grb2', 'grib/multi_1.glo_30m.tp.200703.grb2', 'grib/multi_1.glo_30m.tp.200704.grb2', 'grib/multi_1.glo_30m.tp.200705.grb2', 'grib/multi_1.glo_30m.tp.200706.grb2', 'grib/multi_1.glo_30m.tp.200707.grb2', 'grib/multi_1.glo_30m.tp.200708.grb2', 'grib/multi_1.glo_30m.tp.200709.grb2', 'grib/multi_1.glo_30m.tp.200710.grb2', 'grib/multi_1.glo_30m.tp.200711.grb2', 'grib/multi_1.glo_30m.tp.200712.grb2', 'grib/multi_1.glo_30m.tp.200801.grb2', 'grib/multi_1.glo_30m.tp.200802.grb2', 'grib/multi_1.glo_30m.tp.200803.grb2', 'grib/multi_1.glo_30m.tp.200804.grb2', 'grib/multi_1.glo_30m.tp.200805.grb2', 'grib/multi_1.glo_30m.tp.200806.grb2', 'grib/multi_1.glo_30m.tp.200807.grb2', 'grib/multi_1.glo_30m.tp.200808.grb2', 'grib/multi_1.glo_30m.tp.200809.grb2', 'grib/multi_1.glo_30m.tp.200810.grb2', 'grib/multi_1.glo_30m.tp.200811.grb2', 'grib/multi_1.glo_30m.tp.200812.grb2', 'grib/multi_1.glo_30m.tp.200901.grb2', 'grib/multi_1.glo_30m.tp.200902.grb2', 'grib/multi_1.glo_30m.tp.200903.grb2', 'grib/multi_1.glo_30m.tp.200904.grb2', 'grib/multi_1.glo_30m.tp.200905.grb2', 'grib/multi_1.glo_30m.tp.200906.grb2', 'grib/multi_1.glo_30m.tp.200907.grb2', 'grib/multi_1.glo_30m.tp.200908.grb2', 'grib/multi_1.glo_30m.tp.200909.grb2', 'grib/multi_1.glo_30m.tp.200910.grb2', 'grib/multi_1.glo_30m.tp.200911.grb2', 'grib/multi_1.glo_30m.tp.200912.grb2', 'grib/multi_1.glo_30m.tp.201001.grb2', 'grib/multi_1.glo_30m.tp.201002.grb2', 'grib/multi_1.glo_30m.tp.201003.grb2', 'grib/multi_1.glo_30m.tp.201004.grb2', 'grib/multi_1.glo_30m.tp.201005.grb2', 'grib/multi_1.glo_30m.tp.201006.grb2', 'grib/multi_1.glo_30m.tp.201007.grb2', 'grib/multi_1.glo_30m.tp.201008.grb2', 'grib/multi_1.glo_30m.tp.201009.grb2', 'grib/multi_1.glo_30m.tp.201010.grb2', 'grib/multi_1.glo_30m.tp.201011.grb2', 'grib/multi_1.glo_30m.tp.201012.grb2', 'grib/multi_1.glo_30m.tp.201101.grb2', 'grib/multi_1.glo_30m.tp.201102.grb2', 'grib/multi_1.glo_30m.tp.201103.grb2', 'grib/multi_1.glo_30m.tp.201104.grb2', 'grib/multi_1.glo_30m.tp.201105.grb2', 'grib/multi_1.glo_30m.tp.201106.grb2', 'grib/multi_1.glo_30m.tp.201107.grb2', 'grib/multi_1.glo_30m.tp.201108.grb2', 'grib/multi_1.glo_30m.tp.201109.grb2', 'grib/multi_1.glo_30m.tp.201110.grb2', 'grib/multi_1.glo_30m.tp.201111.grb2', 'grib/multi_1.glo_30m.tp.201112.grb2', 'grib/multi_1.glo_30m.tp.201201.grb2', 'grib/multi_1.glo_30m.tp.201202.grb2', 'grib/multi_1.glo_30m.tp.201203.grb2', 'grib/multi_1.glo_30m.tp.201204.grb2', 'grib/multi_1.glo_30m.tp.201205.grb2', 'grib/multi_1.glo_30m.tp.201206.grb2', 'grib/multi_1.glo_30m.tp.201207.grb2', 'grib/multi_1.glo_30m.tp.201208.grb2', 'grib/multi_1.glo_30m.tp.201209.grb2', 'grib/multi_1.glo_30m.tp.201210.grb2', 'grib/multi_1.glo_30m.tp.201211.grb2', 'grib/multi_1.glo_30m.tp.201212.grb2', 'grib/multi_1.glo_30m.tp.201301.grb2', 'grib/multi_1.glo_30m.tp.201302.grb2', 'grib/multi_1.glo_30m.tp.201303.grb2', 'grib/multi_1.glo_30m.tp.201304.grb2', 'grib/multi_1.glo_30m.tp.201305.grb2', 'grib/multi_1.glo_30m.tp.201306.grb2', 'grib/multi_1.glo_30m.tp.201307.grb2', 'grib/multi_1.glo_30m.tp.201308.grb2', 'grib/multi_1.glo_30m.tp.201309.grb2', 'grib/multi_1.glo_30m.tp.201310.grb2', 'grib/multi_1.glo_30m.tp.201311.grb2', 'grib/multi_1.glo_30m.tp.201312.grb2', 'grib/multi_1.glo_30m.tp.201401.grb2', 'grib/multi_1.glo_30m.tp.201402.grb2', 'grib/multi_1.glo_30m.tp.201403.grb2', 'grib/multi_1.glo_30m.tp.201404.grb2', 'grib/multi_1.glo_30m.tp.201405.grb2', 'grib/multi_1.glo_30m.tp.201406.grb2', 'grib/multi_1.glo_30m.tp.201407.grb2', 'grib/multi_1.glo_30m.tp.201408.grb2', 'grib/multi_1.glo_30m.tp.201409.grb2', 'grib/multi_1.glo_30m.tp.201410.grb2', 'grib/multi_1.glo_30m.tp.201411.grb2', 'grib/multi_1.glo_30m.tp.201412.grb2', 'grib/multi_1.glo_30m.tp.201501.grb2', 'grib/multi_1.glo_30m.tp.201502.grb2', 'grib/multi_1.glo_30m.tp.201503.grb2', 'grib/multi_1.glo_30m.tp.201504.grb2', 'grib/multi_1.glo_30m.tp.201505.grb2', 'grib/multi_1.glo_30m.tp.201506.grb2', 'grib/multi_1.glo_30m.tp.201507.grb2', 'grib/multi_1.glo_30m.tp.201508.grb2', 'grib/multi_1.glo_30m.tp.201509.grb2', 'grib/multi_1.glo_30m.tp.201510.grb2', 'grib/multi_1.glo_30m.tp.201511.grb2', 'grib/multi_1.glo_30m.tp.201512.grb2', 'grib/multi_1.glo_30m.tp.201601.grb2', 'grib/multi_1.glo_30m.tp.201602.grb2', 'grib/multi_1.glo_30m.tp.201603.grb2', 'grib/multi_1.glo_30m.tp.201604.grb2', 'grib/multi_1.glo_30m.tp.201605.grb2', 'grib/multi_1.glo_30m.tp.201606.grb2', 'grib/multi_1.glo_30m.tp.201607.grb2', 'grib/multi_1.glo_30m.tp.201608.grb2', 'grib/multi_1.glo_30m.tp.201609.grb2', 'grib/multi_1.glo_30m.tp.201610.grb2', 'grib/multi_1.glo_30m.tp.201611.grb2', 'grib/multi_1.glo_30m.tp.201612.grb2', 'grib/multi_1.glo_30m.tp.201701.grb2', 'grib/multi_1.glo_30m.tp.201702.grb2', 'grib/multi_1.glo_30m.tp.201703.grb2', 'grib/multi_1.glo_30m.tp.201704.grb2', 'grib/multi_1.glo_30m.tp.201705.grb2', 'grib/multi_1.glo_30m.tp.201706.grb2', 'grib/multi_1.glo_30m.tp.201707.grb2', 'grib/multi_1.glo_30m.tp.201708.grb2', 'grib/multi_1.glo_30m.tp.201709.grb2', 'grib/multi_1.glo_30m.tp.201710.grb2', 'grib/multi_1.glo_30m.tp.201711.grb2', 'grib/multi_1.glo_30m.tp.201712.grb2']





In [10]:
import numpy.ma as ma
import numpy
import pygrib

list=[]
griblist_tp = tp_gribs
for grib in griblist_tp:
    grbs=pygrib.open(grib)
    grbs.read(1)[0]# Remember that indexing in Python starts at zero.
    gmsg = grbs.messages
    
    for i in range(gmsg):
        grb = grbs.select()[i]
        data=grb.values
        lat,lon = grb.latlons()

        data, lats, lons = grb.data(lat1=1.6,lat2=2.2,lon1=202.5,lon2=202.9)
        list.append(ma.getdata(data))
        tp_all0 = numpy.hstack(list)
    print grib
    
tp_all = tp_all0.ravel()

numpy.save('tp_all_0360.npy',tp_all)

grib/multi_1.glo_30m.tp.200502.grb2
grib/multi_1.glo_30m.tp.200503.grb2
grib/multi_1.glo_30m.tp.200504.grb2
grib/multi_1.glo_30m.tp.200505.grb2
grib/multi_1.glo_30m.tp.200506.grb2
grib/multi_1.glo_30m.tp.200507.grb2
grib/multi_1.glo_30m.tp.200508.grb2
grib/multi_1.glo_30m.tp.200509.grb2
grib/multi_1.glo_30m.tp.200510.grb2
grib/multi_1.glo_30m.tp.200511.grb2
grib/multi_1.glo_30m.tp.200512.grb2
grib/multi_1.glo_30m.tp.200601.grb2
grib/multi_1.glo_30m.tp.200602.grb2
grib/multi_1.glo_30m.tp.200603.grb2
grib/multi_1.glo_30m.tp.200604.grb2
grib/multi_1.glo_30m.tp.200605.grb2
grib/multi_1.glo_30m.tp.200606.grb2
grib/multi_1.glo_30m.tp.200607.grb2
grib/multi_1.glo_30m.tp.200608.grb2
grib/multi_1.glo_30m.tp.200609.grb2
grib/multi_1.glo_30m.tp.200610.grb2
grib/multi_1.glo_30m.tp.200611.grb2
grib/multi_1.glo_30m.tp.200612.grb2
grib/multi_1.glo_30m.tp.200701.grb2
grib/multi_1.glo_30m.tp.200702.grb2
grib/multi_1.glo_30m.tp.200703.grb2
grib/multi_1.glo_30m.tp.200704.grb2
grib/multi_1.glo_30m.tp.2007

In [11]:
import numpy.ma as ma
import numpy
import pygrib

list=[]
griblist_hs = hs_gribs
for grib in griblist_hs:
    grbs=pygrib.open(grib)
    grbs.read(1)[0]# Remember that indexing in Python starts at zero.
    gmsg = grbs.messages
    
    for i in range(gmsg):
        grb = grbs.select()[i]
        data=grb.values
        lat,lon = grb.latlons()

        data, lats, lons = grb.data(lat1=1.6,lat2=2.2,lon1=202.5,lon2=202.9)
        list.append(ma.getdata(data))
        hs_all0 = numpy.hstack(list)
    print grib
    
hs_all = hs_all0.ravel()

numpy.save('hs_all_0360.npy',hs_all)

grib/multi_1.glo_30m.hs.200502.grb2
grib/multi_1.glo_30m.hs.200503.grb2
grib/multi_1.glo_30m.hs.200504.grb2
grib/multi_1.glo_30m.hs.200505.grb2
grib/multi_1.glo_30m.hs.200506.grb2
grib/multi_1.glo_30m.hs.200507.grb2
grib/multi_1.glo_30m.hs.200508.grb2
grib/multi_1.glo_30m.hs.200509.grb2
grib/multi_1.glo_30m.hs.200510.grb2
grib/multi_1.glo_30m.hs.200511.grb2
grib/multi_1.glo_30m.hs.200512.grb2
grib/multi_1.glo_30m.hs.200601.grb2
grib/multi_1.glo_30m.hs.200602.grb2
grib/multi_1.glo_30m.hs.200603.grb2
grib/multi_1.glo_30m.hs.200604.grb2
grib/multi_1.glo_30m.hs.200605.grb2
grib/multi_1.glo_30m.hs.200606.grb2
grib/multi_1.glo_30m.hs.200607.grb2
grib/multi_1.glo_30m.hs.200608.grb2
grib/multi_1.glo_30m.hs.200609.grb2
grib/multi_1.glo_30m.hs.200610.grb2
grib/multi_1.glo_30m.hs.200611.grb2
grib/multi_1.glo_30m.hs.200612.grb2
grib/multi_1.glo_30m.hs.200701.grb2
grib/multi_1.glo_30m.hs.200702.grb2
grib/multi_1.glo_30m.hs.200703.grb2
grib/multi_1.glo_30m.hs.200704.grb2
grib/multi_1.glo_30m.hs.2007

In [12]:
import numpy.ma as ma
import numpy
import pygrib

list=[]
griblist_dp = dp_gribs
for grib in griblist_dp:
    grbs=pygrib.open(grib)
    grbs.read(1)[0]# Remember that indexing in Python starts at zero.
    gmsg = grbs.messages
    
    for i in range(gmsg):
        grb = grbs.select()[i]
        data=grb.values
        lat,lon = grb.latlons()

        data, lats, lons = grb.data(lat1=1.6,lat2=2.2,lon1=202.5,lon2=202.9)
        list.append(ma.getdata(data))
        dp_all0 = numpy.hstack(list)
    print grib
    
dp_all = dp_all0.ravel()

numpy.save('dp_all_0360.npy',dp_all)

grib/multi_1.glo_30m.dp.200502.grb2
grib/multi_1.glo_30m.dp.200503.grb2
grib/multi_1.glo_30m.dp.200504.grb2
grib/multi_1.glo_30m.dp.200505.grb2
grib/multi_1.glo_30m.dp.200506.grb2
grib/multi_1.glo_30m.dp.200507.grb2
grib/multi_1.glo_30m.dp.200508.grb2
grib/multi_1.glo_30m.dp.200509.grb2
grib/multi_1.glo_30m.dp.200510.grb2
grib/multi_1.glo_30m.dp.200511.grb2
grib/multi_1.glo_30m.dp.200512.grb2
grib/multi_1.glo_30m.dp.200601.grb2
grib/multi_1.glo_30m.dp.200602.grb2
grib/multi_1.glo_30m.dp.200603.grb2
grib/multi_1.glo_30m.dp.200604.grb2
grib/multi_1.glo_30m.dp.200605.grb2
grib/multi_1.glo_30m.dp.200606.grb2
grib/multi_1.glo_30m.dp.200607.grb2
grib/multi_1.glo_30m.dp.200608.grb2
grib/multi_1.glo_30m.dp.200609.grb2
grib/multi_1.glo_30m.dp.200610.grb2
grib/multi_1.glo_30m.dp.200611.grb2
grib/multi_1.glo_30m.dp.200612.grb2
grib/multi_1.glo_30m.dp.200701.grb2
grib/multi_1.glo_30m.dp.200702.grb2
grib/multi_1.glo_30m.dp.200703.grb2
grib/multi_1.glo_30m.dp.200704.grb2
grib/multi_1.glo_30m.dp.2007